version: '3.8'

services:

  db:
    container_name: db
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    container_name: web
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    container_name: nginx
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/

    depends_on:
      - web

  backup:
    container_name: backup
    image: bitnami/minideb
    volumes:
      - ./backup.sh:/usr/local/bin/backup.sh
      - backups:/backup
    entrypoint: ["bash", "-c", "apt-get update && apt-get install -y cron && echo '17 57 * * * /usr/local/bin/backup.sh' > /etc/cron.d/db_backup && crontab /etc/cron.d/db_backup && cron -f"]
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  static_value:
  media_value:
  backups: