# Generated by Django 5.0.3 on 2024-05-17 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.board')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.board')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.stage')),
            ],
        ),
        migrations.CreateModel(
            name='StageComponentsQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.component')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.stage')),
            ],
            options={
                'unique_together': {('component', 'stage')},
            },
        ),
        migrations.AddField(
            model_name='stage',
            name='component',
            field=models.ManyToManyField(through='production.StageComponentsQuantity', to='catalog.component'),
        ),
    ]
