# Generated by Django 5.0.3 on 2024-05-20 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_verbose_names'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': 'Плата', 'verbose_name_plural': 'Платы'},
        ),
        migrations.AlterModelOptions(
            name='production',
            options={'verbose_name': 'Текущее производство: статус и количество', 'verbose_name_plural': 'Текущее производство: статус и количество'},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'verbose_name': 'Этап производства', 'verbose_name_plural': 'Этапы производства'},
        ),
        migrations.AlterModelOptions(
            name='stagecomponentsquantity',
            options={'verbose_name': 'Схема: Связь этапа и количества компонентов', 'verbose_name_plural': 'Схема: Связь этапа и количества компонентов'},
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='production',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.board', verbose_name='Плата'),
        ),
        migrations.AlterField(
            model_name='production',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество на этапе'),
        ),
        migrations.AlterField(
            model_name='production',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.stage', verbose_name='Этап производства'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.board', verbose_name='Плата'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='component',
            field=models.ManyToManyField(through='production.StageComponentsQuantity', to='catalog.component', verbose_name='Компонент'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='stagecomponentsquantity',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.component', verbose_name='Компонент'),
        ),
        migrations.AlterField(
            model_name='stagecomponentsquantity',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество компонента на этап'),
        ),
        migrations.AlterField(
            model_name='stagecomponentsquantity',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.stage', verbose_name='Этап'),
        ),
    ]
