# Generated by Django 5.0.3 on 2024-05-20 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_verbose_names'),
        ('production', '0002_verbose_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stagecomponentsquantity',
            options={'verbose_name': 'Схема: Связь этапа, платы и количества компонентов', 'verbose_name_plural': 'Схема: Связь этапа, платы и количества компонентов'},
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='component',
            new_name='board_component',
        ),
        migrations.AlterUniqueTogether(
            name='stagecomponentsquantity',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='stage',
            name='board',
        ),
        migrations.AddField(
            model_name='stagecomponentsquantity',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.board', verbose_name='Плата'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='stagecomponentsquantity',
            unique_together={('component', 'stage', 'board')},
        ),
    ]
