# Generated by Django 5.0.3 on 2024-05-20 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_verbose_names'),
        ('production', '0004_test_faild'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='board',
        ),
        migrations.CreateModel(
            name='StageComponentBoardQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество компонента на этап')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.board', verbose_name='Плата')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.component', verbose_name='Компонент')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.stage', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Схема: Связь этапа и количества компонентов',
                'verbose_name_plural': 'Схема: Связь этапа и количества компонентов',
                'unique_together': {('component', 'stage')},
            },
        ),
        migrations.AlterField(
            model_name='stage',
            name='component',
            field=models.ManyToManyField(through='production.StageComponentBoardQuantity', to='catalog.component', verbose_name='Компоненты и платы'),
        ),
        migrations.DeleteModel(
            name='StageComponentsQuantity',
        ),
    ]
