# Generated by Django 5.0.3 on 2024-05-21 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_verbose_names'),
        ('production', '0005_mtm_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='component',
        ),
        migrations.AlterUniqueTogether(
            name='stagecomponentboardquantity',
            unique_together={('component', 'stage', 'board')},
        ),
    ]
