# Generated by Django 5.0.3 on 2024-05-21 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_verbose_names'),
        ('production', '0006_finally_guess'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stagecomponentboardquantity',
            unique_together={('stage', 'board')},
        ),
        migrations.AlterField(
            model_name='stagecomponentboardquantity',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.component', verbose_name='Компонент'),
        ),
    ]
