# Generated by Django 5.0.3 on 2024-05-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_finally_guess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(help_text='Уникальное название платы, не более 30 символов', max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='production',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Количество заданных плат на этом этапе', verbose_name='Количество на этапе'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(help_text='Уникальное название этапа, не более 256 символов', max_length=256, verbose_name='Название'),
        ),
    ]
