# Generated by Django 5.0.3 on 2024-05-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_order_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='slug',
            field=models.SlugField(default=1, help_text='Уникальный слаг платы, не более 30 символов', max_length=30, verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
