# Generated by Django 5.0.3 on 2024-05-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_slug_board'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ('order',), 'verbose_name': 'Этап производства', 'verbose_name_plural': 'Этапы производства'},
        ),
        migrations.AddField(
            model_name='stage',
            name='cable_stage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, help_text='Порядок выполнения этапов, от 1 до бесконечности', verbose_name='Порядок этапа'),
            preserve_default=False,
        ),
    ]
