# Generated by Django 5.0.3 on 2024-06-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_board_cable_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='quantity',
            field=models.IntegerField(help_text='Количество заданных плат на этом этапе', verbose_name='Количество на этапе'),
        ),
        migrations.AlterField(
            model_name='stagecomponentboardquantity',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество компонента на этап'),
        ),
    ]
