# Generated by Django 5.0.3 on 2024-06-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_change_positive_integer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Количество заданных плат на этом этапе', verbose_name='Количество на этапе'),
        ),
        migrations.AlterField(
            model_name='stagecomponentboardquantity',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество компонента на этап'),
        ),
    ]
