# Generated by Django 5.0.3 on 2024-06-11 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_alter_production_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(help_text='Номер приложения по докам', verbose_name='Номер приложения')),
                ('board_quantity', models.PositiveIntegerField(help_text='Сколько конкретно данных плат заказано', verbose_name='Количество заказанных плат')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.board', verbose_name='Плата')),
            ],
            options={
                'verbose_name': 'Приложение',
                'verbose_name_plural': 'Приложения',
                'ordering': ('number',),
            },
        ),
        migrations.AddField(
            model_name='production',
            name='document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.document', verbose_name='Номер прилы'),
            preserve_default=False,
        ),
    ]
