# Generated by Django 5.0.3 on 2024-06-20 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_add_document_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='board',
        ),
        migrations.RemoveField(
            model_name='document',
            name='board_quantity',
        ),
        migrations.CreateModel(
            name='DocumentBoardQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_quantity', models.PositiveIntegerField(help_text='Сколько конкретно данных плат заказано', verbose_name='Количество заказанных плат')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.board', verbose_name='Плата')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.document', verbose_name='Номер приложения')),
            ],
            options={
                'verbose_name': 'Приложение',
                'verbose_name_plural': 'Приложения',
                'ordering': ('document',),
            },
        ),
    ]
