# Generated by Django 5.0.3 on 2024-06-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_change_doc_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Отправлено заказчику'),
        ),
        migrations.DeleteModel(
            name='DocumentBoardQuantity',
        ),
    ]
