# Generated by Django 5.0.3 on 2024-07-25 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_delete_documentboard_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='production',
            unique_together={('stage', 'board', 'document')},
        ),
    ]
