# Generated by Django 5.0.3 on 2024-07-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_catalog_addfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='central_q',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Количество центральных', null=True, verbose_name='Количество центральных'),
        ),
        migrations.AddField(
            model_name='document',
            name='facial_q',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Количество лицевых', null=True, verbose_name='Количество лицевых'),
        ),
        migrations.AddField(
            model_name='document',
            name='indicator_q',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Количество индикаторных', null=True, verbose_name='Количество индикаторных'),
        ),
        migrations.AddField(
            model_name='document',
            name='round_q',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Количество круглых', null=True, verbose_name='Количество круглых'),
        ),
    ]
