# Generated by Django 5.0.3 on 2024-07-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_catalog_addfield'),
        ('production', '0017_doc_boards_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='number',
            field=models.PositiveSmallIntegerField(help_text='Номер приложения по докам', unique=True, verbose_name='Номер приложения'),
        ),
        migrations.AlterUniqueTogether(
            name='stagecomponentboardquantity',
            unique_together={('stage', 'board', 'component')},
        ),
    ]
