# Generated by Django 5.0.3 on 2024-03-26 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ComponentQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.IntegerField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.board')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.component')),
            ],
            options={
                'unique_together': {('component', 'board')},
            },
        ),
        migrations.AddField(
            model_name='board',
            name='components',
            field=models.ManyToManyField(through='catalog.ComponentQuantity', to='catalog.component'),
        ),
    ]
