# Generated by Django 5.0.3 on 2024-05-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_verbose_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ('name',), 'verbose_name': 'Компонент', 'verbose_name_plural': 'Компоненты'},
        ),
        migrations.AlterField(
            model_name='component',
            name='critical_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Когда уже пора заказывать', null=True, verbose_name='Критическое количество'),
        ),
        migrations.AlterField(
            model_name='component',
            name='description',
            field=models.TextField(blank=True, help_text='Не обязательное поле, описание', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(help_text='Уникальное название компонента, не более 50 символов', max_length=50, verbose_name='Название'),
        ),
    ]
