# Generated by Django 5.0.3 on 2024-06-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_order_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество на складе'),
        ),
    ]
