# Generated by Django 5.0.3 on 2024-07-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_change_positive_integer'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='part_number',
            field=models.CharField(default=123456, help_text='Пример: "CL10B104KB8NNNC"', max_length=50, verbose_name='Номер партии'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(help_text='Схема названия: "Part | Footprint"', max_length=50, verbose_name='Название'),
        ),
    ]
