# Generated by Django 5.0.3 on 2024-08-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_catalog_addfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(help_text='Схема названия: "Part | Footprint"', max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
